image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - /^master/@iris/lambda-rust
  - /^ci/@iris/lambda-rust
  except:
  - triggers
  - schedules
  - api

## Build jobs

# We are in Coq's benchmark suite, so better make sure we keep working with Coq master.
build-coq.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version dev   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#step_indexing_controlled_by_ghosts"

build-coq.8.12.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.0   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#step_indexing_controlled_by_ghosts"
    OPAM_PKG: "1"
    DENY_WARNINGS: "1"
  tags:
  - fp-timing

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version dev   coq-stdpp.dev git git+https://gitlab.mpi-sws.org/iris/stdpp.git#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#step_indexing_controlled_by_ghosts"
  only:
  - triggers
  - schedules
  - api
